# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  schedule:
  - cron: '10 7 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: node --unhandled-rejections=strict . "Edmonton" "Red Deer"
      env:
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        TWILIO_PHONE: ${{ secrets.TWILIO_PHONE }}
        USER_FNAME: ${{ secrets.USER_FNAME }}
        USER_LNAME: ${{ secrets.USER_LNAME }}
        USER_MVID: ${{ secrets.USER_MVID }}
        USER_BIRTH: ${{ secrets.USER_BIRTH }}
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
        USER_PHONE: ${{ secrets.USER_PHONE }}
        USER_TEST: ${{ secrets.USER_TEST }}
        USER_RADIUS: ${{ secrets.USER_RADIUS }}
    - uses: actions/upload-artifact@v2
      with:
        name: Screenshot
        path: ./result.png
